### ISSUE TITLE
Pin stable Black dependency

### ISSUE THREAD

**Issue by bm424** [hukkinj1/mdformat-black#3]
Hey! Great tool, super useful for keeping code and docs consistent.

Black's just released its [first stable version](https://black.readthedocs.io/en/stable/change_log.html#id1). Would it be possible to take advantage of the stability and pin the dependency?

https://github.com/hukkin/mdformat-black/blob/2301bf77de8edb0d9440d8abee4ccf9129c2694a/pyproject.toml#L35

**Comment by hukkin** [comment]
Hey, thanks for the issue!

I don't think it's a good idea to pin black. I think users should pin black if they want (and me pinning would be in conflict with that).

mdformat-black uses whatever version of black is installed, so to pin black you should do e.g.
```bash
pip install mdformat-black black==22.1.0
```
or if you're using pre-commit, configure it like
```yaml
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.13
  hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-black
        - black==22.1.0
```
